Task/07 adzhima nikita
mipt-backend-academy-winter-2023/team-1 pull request #18
Opened 2023-10-25 17:21 UTC by Nikitadzhima

2023-10-26 10:52 UTC, kirillgrachoff commented on photos/photos.Dockerfile
> +# не знаю что тут происходит, но это ломает Build Docker в CI, тк по такому пути не находятся файлы, временно закоментил
Это значит, что контейнер не собирается.

Здесь происходит копирование артефактов сборки куда надо. (оттуда ли надо копировать, не ясно)

2023-11-09 09:11 UTC, Drakohka95 commented on .github/workflows/ci.yaml
> +          sbt test
рекомендуется разнести по разным степам (либо и вовсе джобам)

ибо если упал линтер - тесты все равно хочется прогонять

2023-11-09 09:13 UTC, Drakohka95 commented on photos/photos.Dockerfile
> +#COPY --from=builder /workspace/photos/target/scala-2.13/*.jar .
сейчас ок, но в домашке на балансер надо будет починить

2023-11-09 09:16 UTC, Drakohka95 commented on src/test/scala/TestApp.scala
> +object ExampleSpec extends ZIOSpecDefault {
для проверки как работает (и работает ли) в ci - sbt test - ок
как конечный вариант домашки "Написать тесты для своего приложения" не ок

2023-11-09 09:24 UTC, Drakohka95 reviewed
На данный момент 2 из 3 (ci добавил, работает корректно. тестовые либы подключил, скелет тестов добавил)

Чего не хватает: адекватных тестов, хотя бы на один сервис
Желательно: разнести в ci прогон тестов и проверку линтером

2023-11-14 15:01 UTC, Nikitadzhima commented on photos/photos.Dockerfile
> +# не знаю что тут происходит, но это ломает Build Docker в CI, тк по такому пути не находятся файлы, временно закоментил
я разобрался
сервис photos просто забыли добавить в build.sbt ))
поправил и раскомментил эту строчку обратно

2023-11-14 18:31 UTC, Drakohka95 commented on photos/src/main/scala/photos/api/HttpRoutes.scala
> +}
это очень странный линтер. первый раз вижу такое в импортах

2023-11-14 18:39 UTC, Drakohka95 requested changes
в плане ci все прекрасно, очень хочу смержить этот мр  
тестов бы приличных хотя бы на один сервис

2023-11-14 21:29 UTC, Nikitadzhima commented on photos/src/main/scala/photos/api/HttpRoutes.scala
> +}
ага, такой в задании был 🤷‍♂️

2023-11-14 21:30 UTC, Nikitadzhima commented
да, добавлю, не успел доделать сегодня(

2023-11-17 09:08 UTC, Nikitadzhima commented on src/test/scala/TestApp.scala
> +object ExampleSpec extends ZIOSpecDefault {
добавил тест, можно смотреть

2023-11-27 12:09 UTC, Drakohka95 approved these changes

2023-11-27 12:10 UTC, merged